<#
Register-BridgeBriefingToastWatcher.ps1
======================================
Registers the TEMPORARY desktop task "Work Inbox Briefing Toast Watcher" on
DESKTOP-MJDJM64 (user admin). Every 5 minutes it runs Watch-BridgeBriefing.ps1,
which toasts on a new "chore: update briefing" commit for data/briefing.json
AND on a laptop briefing / draft-diff FAILURE (data/laptop_status/*.json).
Independent of the desktop's own tasks (which stay Disabled during the bridge).

Run ONCE in a normal (non-elevated) PowerShell as the desktop 'admin' user.

Expects the live script at:
  D:\OneDrive - lelitte.com\Desktop\Watch-BridgeBriefing.ps1

The task action is wscript.exe + a generated hidden VBS wrapper -- NOT a direct
powershell.exe action. A direct powershell.exe action (even -WindowStyle Hidden)
flashes a console window every 5 minutes; WScript.Shell.Run windowStyle=0 does
not. This register script (re)writes "Watch-BridgeBriefing-Hidden.vbs" next to
the live .ps1 every time it runs, so a redeploy can't reintroduce the flash.
Same rule for any future frequently-firing scheduled task: wrap in wscript+VBS.

UNREGISTER (end of bridge):
  Unregister-ScheduledTask -TaskName 'Work Inbox Briefing Toast Watcher' -Confirm:$false
  Remove-Item 'D:\OneDrive - lelitte.com\Desktop\Watch-BridgeBriefing-Hidden.vbs' -ErrorAction SilentlyContinue
#>
$ErrorActionPreference = 'Stop'
$taskName = 'Work Inbox Briefing Toast Watcher'
$live     = 'D:\OneDrive - lelitte.com\Desktop\Watch-BridgeBriefing.ps1'
$vbs      = 'D:\OneDrive - lelitte.com\Desktop\Watch-BridgeBriefing-Hidden.vbs'

if (-not (Test-Path $live)) {
  throw "live script not found: $live  --  download it there first (see Drew's handover)."
}

# (Re)generate the hidden VBS wrapper next to the live script. Synchronous +
# WScript.Quit so LastTaskResult is meaningful and the poll isn't torn down
# mid-run when wscript.exe exits.
$vbsBody = @"
' Auto-generated by Register-BridgeBriefingToastWatcher.ps1 -- do not edit by hand.
' Hidden launcher for "$taskName": WScript.Shell.Run windowStyle=0 so the 5-min
' poll never flashes a console window (a direct powershell.exe task action does,
' even with -WindowStyle Hidden). Matches the "Run X Hidden.vbs" pattern used by
' every other work-inbox desktop task.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$(Split-Path $live -Parent)"
rc = sh.Run("powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$live""", 0, True)
WScript.Quit(rc)
"@
Set-Content -LiteralPath $vbs -Value $vbsBody -Encoding ASCII
Write-Host "Wrote hidden VBS wrapper: $vbs"

$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbs`""

# every 5 minutes, indefinitely
$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
  -RepetitionInterval (New-TimeSpan -Minutes 5) -RepetitionDuration (New-TimeSpan -Days 3650)

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
  -LogonType Interactive -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
  -MultipleInstances IgnoreNew `
  -ExecutionTimeLimit (New-TimeSpan -Minutes 3) `
  -StartWhenAvailable `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -DontStopOnIdleEnd

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
  -Principal $principal -Settings $settings -Force `
  -Description 'TEMPORARY bridge-period watcher: toasts on a new GitHub "chore: update briefing" commit and on a laptop briefing/draft-diff FAILURE while the work-inbox pipeline runs on the laptop. Read-only GitHub poll, no Outlook/M365. Runs via wscript.exe + hidden VBS (no console flash). Remove when the pipeline has a permanent home.'

Write-Host "Registered '$taskName' (every 5 min via wscript.exe hidden VBS, as $env:USERDOMAIN\$env:USERNAME, run-only-when-logged-on)."
Write-Host "Smoke test now:  Start-ScheduledTask -TaskName '$taskName'  ;  Get-Content `"$env:LOCALAPPDATA\WorkInboxAI\bridge_toast_watcher.log`" -Tail 5"
Write-Host "(first run seeds the last-seen SHAs silently; the next NEW briefing commit / a FAILED status file produces the first toast.)"
