<#
Register-LaptopDraftDiff.ps1
============================
Registers the scheduled task "Work Inbox Laptop Draft Diff" on Kevin's Oxford
laptop (101L-DE013193 / begb0037.AD-OAK). It runs "Run Laptop Draft Diff.ps1":
the ongoing draft/final diff capture, reading Drafts + Sent over IMAP+OAuth2
(no Outlook COM). Writes/logs only, plus one tiny GitHub run-status file
(data/laptop_status/draftdiff_status.json -- counts + exit code, no email content).

RUN THIS ONCE, in a normal (NON-elevated) PowerShell, signed in as ad-oak\begb0037
(the PRT-holding standard user -- NOT begb0037-a).

  -Cadence Bridge  (default)  07:30 / 12:30 / 16:30 Mon-Fri   (3x/day, each 30 min
                              after a "Work Inbox Bridge Briefing" slot -- same
                              stagger logic as the desktop's original 06:30/09:30/... offset)
  -Cadence Full               06:30 / 09:30 / 12:30 / 15:30 / 18:30 Mon-Fri   (matches the
                              desktop "Draft Diff Capture" task exactly)

  -NoAI            pass -NoAI through to the wrapper: correlation + redaction
                   only, no `claude -p` enrichment (pairs stage for later).
                   DEFAULT is enrichment ON via headless `claude -p`
                   (subscription auth, CLAUDE_CONFIG_DIR=C:\WorkInboxAI\kevin,
                   ANTHROPIC_API_KEY stripped -- no metered key needed).

LogonType = Interactive: runs only while ad-oak\begb0037 is logged on -- required
for the MSAL broker silent-token path AND the `claude -p` subscription session.
Keep the laptop docked + logged in.
StartWhenAvailable is deliberately OFF (mirrors the desktop task): a skipped
catch-up costs nothing -- Thread-Index correlation picks up any pending pair on
the next real run.

UNREGISTER:
  Unregister-ScheduledTask -TaskName 'Work Inbox Laptop Draft Diff' -Confirm:$false
Then on the admin desktop (to restore the old path):
  Enable-ScheduledTask -TaskName 'Draft Diff Capture'
#>
param(
  [ValidateSet('Bridge','Full')] [string]$Cadence = 'Bridge',
  [switch]$NoAI
)

$ErrorActionPreference = 'Stop'
$taskName = 'Work Inbox Laptop Draft Diff'
$root     = Join-Path $env:USERPROFILE 'work-inbox'
$wrapper  = Join-Path $root 'Run Laptop Draft Diff.ps1'

if (-not (Test-Path $wrapper)) {
  throw "wrapper not found: $wrapper  --  copy 'Run Laptop Draft Diff.ps1' AND 'Push-LaptopRunStatus.ps1' into $root first (see Drew's handover)."
}
if (-not (Test-Path (Join-Path $root 'Push-LaptopRunStatus.ps1'))) {
  throw "Push-LaptopRunStatus.ps1 not found next to the wrapper in $root -- copy it there too (the wrapper calls it for the run-status file)."
}

$times = if ($Cadence -eq 'Full') { '06:30','09:30','12:30','15:30','18:30' } else { '07:30','12:30','16:30' }

$psArgs = "-NoProfile -ExecutionPolicy Bypass -File `"`"$wrapper`"`""
if ($NoAI) { $psArgs += ' -NoAI' }
$psArgs += " -Cadence $Cadence"

# Task action = wscript.exe + a generated hidden VBS, NOT a direct powershell.exe
# action. A direct powershell.exe action flashes a console window on each fire
# (even -WindowStyle Hidden); WScript.Shell.Run windowStyle=0 does not. Matches
# the "Run X Hidden.vbs" pattern every other work-inbox scheduled task uses.
$vbs = Join-Path $root 'Run Laptop Draft Diff-Hidden.vbs'
$vbsBody = @"
' Auto-generated by Register-LaptopDraftDiff.ps1 -- do not edit by hand.
' Hidden launcher for "$taskName": WScript.Shell.Run windowStyle=0 so the
' scheduled run never flashes a console window. Synchronous + WScript.Quit so
' LastTaskResult reflects the real result and Task Scheduler doesn't tear the
' run down when wscript.exe exits.
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "$root"
rc = sh.Run("powershell.exe $psArgs", 0, True)
WScript.Quit(rc)
"@
Set-Content -LiteralPath $vbs -Value $vbsBody -Encoding ASCII
Write-Host "Wrote hidden VBS wrapper: $vbs"

$action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbs`""

$triggers = foreach ($tm in $times) {
  New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday -At $tm
}

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
  -LogonType Interactive -RunLevel Limited

# StartWhenAvailable intentionally NOT set (mirrors the desktop 'Draft Diff Capture').
$settings = New-ScheduledTaskSettingsSet `
  -MultipleInstances IgnoreNew `
  -ExecutionTimeLimit (New-TimeSpan -Minutes 20) `
  -DontStopOnIdleEnd `
  -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $triggers `
  -Principal $principal -Settings $settings -Force `
  -Description "work-inbox draft/final diff capture on the laptop over IMAP (no Outlook COM). Writes local-only staging + one tiny GitHub run-status file. Replaces the desktop 'Draft Diff Capture' task -- disable that once this is proven."

Write-Host "Registered '$taskName'  (cadence: $Cadence -> $($times -join ', ') Mon-Fri, enrichment=$(if($NoAI){'OFF (-NoAI)'}else{'claude -p'}), as $env:USERDOMAIN\$env:USERNAME, run-only-when-logged-on)."
(Get-ScheduledTask -TaskName $taskName).Triggers | Format-Table -AutoSize
Write-Host ""
Write-Host "Smoke test now:  Start-ScheduledTask -TaskName '$taskName'"
Write-Host "Then watch:      Get-Content `"$root\logs\draft_diff_last_run.log`" -Wait"
